const tokenMap ={
    INTEGER :  "INTEGER",
    OP :  "OP",
    EOF :  "EOF",
    LEFTPARENT :  "(",
    RIGHTPARENT :  ")",
    IDENTIFIER :  "IDENTIFIER",
    WHITESPACE :  " ",
    EQUAL: "=",
    SEMI: ";",
    NEWLINE: "\n",
    WHILE_KEYWORD: "while",
    LEFTCURL: "{",
    RIGHTCURL: "}",
    SWITCH_KEYWORD: "switch",
    COLON: ",",
    CASE_KEYWORD: "case",
    BREAK_KEYWORD: "break",
    DEFAULT_KEYWORD: "default",
    GREATER_THAN: ">",
    LESS_THAN: "<",
    NOT: "!",
    GREATER_THAN_EQUAL: ">=",
    LESS_THAN_EQUAL: "<=",
    NOT_EQUAL: "!=",
    STRICT_EQUAL: "===",
    LOOSE_EQUAL: "==",
    IF_KEYWORD: "if",
    ELSE_KEYWORD: "else",
    DO_KEYWORD: "do",
    OR: "||",
    AND: "&&"
}
export default tokenMap